spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/QianXun0827/SpringCloudConfig
          searchPaths: QianXun
          username: QianXun0827
          password: qqvnysfa53

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

